### ISSUE TITLE
Option for dd-mm-yyyy date format.

### ISSUE THREAD

**Issue by flomax** [Epholys/ultz#2]
Heya. Great extension, I find it incredibly useful dealing with some overseas clients. 

That said, would it be possible to extend the functionality of the [datetime] format to allow **dd-mm-yyyy** input ? 

The country I live in uses this format, as does a large chunk of the planet apart from the US it seems :) 
Being able to enter in this format would certainly help my oft-confused brain. All good if it is too much to implement. TIA.

**Comment by Epholys** [comment]
Hello! Thank you, I'm really happy to see that my extension is useful!

That's a tricky request, because the `dd-mm` and `mm-dd` format are ambiguous, it's not possible to distinguishes them just looking at the numbers.

I'm not in the US either, and I wanted some kind of neutral format, so I choose ISO: `yyyy-mm-dd`. However, I made optional the `yyyy-` part, so in the end, it kinda went back to US-style format.

We could add some kind of specific marker to distinguish the two (shorts) formats, like `X mm-dd` and `Y dd-mm`, but I think it would be really confusing. If you have better ideas, please share!

**Comment by flomax** [comment]
Thanks kindly for the thoughtful reply. I agree that it is a tricky obstacle and I unfortunately have very limited & basic coding knowledge. I am very happy to continue using the extensions current MM-DD format of course.

If it there was an easy way to add the ability to switch between input formats that would be a nice "quality of life" improvement :)

My only suggestion would be for a hard toggle like this mockup but I have no idea of difficulty, or any expectation of you, to implement. 

![tz mockup](https://user-images.githubusercontent.com/4483967/106344692-15602a00-62f7-11eb-8f0b-a47b9acf1345.png)

**Comment by Epholys** [comment]
I hadn't thought about an option in the extensions menu!

I implemented it, if you update the extension you should have this new feature. Please tell me if everything works well :)

**Comment by flomax** [comment]
Oh my gosh, this is fantastic. Have updated and tested and all seems to be working well here. 
I cannot begin to express how thankful I am for you doing this.. will surely save me a few brain cycles in the future, and eliminate  chances for error when looking up timeshifts.
Thank you so much Thomas. :+1:
